version: "3.9"

services:

  # Base de dados MySQL de produtos
  produtos-mysql:
    image: "mysql:latest"
    container_name: "produtos-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtos
    networks:
      - services-network-01

  # App de produtos, que usa o MySQL
  produto-app:
    build: ./produto-app/
    depends_on:
      - produtos-mysql
      - eureka-server
    container_name: "produtos-mysql-app-instance"
    networks:
      - services-network-01

  # Base de dados MySQL de usuários
  usuarios-mysql:
    image: "mysql:latest"
    ports:
      - "3307:3306"
    container_name: "usuarios-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    networks:
      - services-network-01

  # App de usuários, que usa o MySQL
  usuario-app:
    build: ./usuario-app/
    depends_on:
      - usuarios-mysql
      - eureka-server
    container_name: "usuarios-mysql-app-instance"
    networks:
      - services-network-01

  # Base de dados Mongo de vendas
  vendas-mongo:
    image: "mongo:latest"
    container_name: "vendas-mongo"
    hostname: "vendas-mongo"
    ports:
      - "27017:27017"
    networks:
      - services-network-01

  # App de vendas, que usa o Mongo
  venda-app:
    build: ./venda-app/
    container_name: "venda-app-instance"
    depends_on:
      - vendas-mongo
      - eureka-server
      - produto-app
      - usuario-app
    ports:
      - "8082:8082"
    networks:
      - services-network-01


# -------- CONFIGURAÇÃO -------- #

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    container_name: "eureka-server"
    networks:
      - services-network-01

  #prometheus:
  #  image: "prom/prometheus"
  #  container_name: prometheus-app
  #  ports:
  #    - "9090:9090"
  #  volumes:
  #    - ./prometheus/:/etc/prometheus
  #    - ./prometheus_data:/prometheus
  #  command:
  #    - '--config.file=/etc/prometheus/prometheus.yml'
  #    - '--storage.tsdb.path=/prometheus'
  #
  #grafana:
  #  container_name: grafana
  #  image: grafana/grafana:latest
  #  volumes:
  #    - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - prometheus

  api-gateway:
    container_name: "api-gateway"
    build: ./api-gateway/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - services-network-01




networks:
  services-network-01:
    name: services-network-01
    driver: bridge