version: "3.9"

services:

  # Base de dados MySQL de produtos
  produtos-mysql:
    image: "mysql:latest"
    container_name: "produtos-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtos
    networks:
      services-network-01:
        aliases:
          - produtos-mysql

  # App de produtos, que usa o MySQL
  produto-app:
    build: ./produto-app/
    ports:
      - "8080:80" 
    depends_on:
      - produtos-mysql
      - eureka-server
    container_name: "produtos-mysql-app-instance"
    networks:
      services-network-01:
        aliases:
          - produtos-service

  # Base de dados MySQL de usuários
  usuarios-mysql:
    image: "mysql:latest"
    ports:
      - "3307:3306"
    container_name: "usuarios-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    networks:
      services-network-01:
        aliases:
          - usuarios-mysql

  # App de usuários, que usa o MySQL
  usuario-app:
    build: ./usuario-app/
    ports:
      - "8081:81"
    depends_on:
      - usuarios-mysql
      - eureka-server
    container_name: "usuarios-mysql-app-instance"
    networks:
      services-network-01:
        aliases:
          - usuarios-service

  # Base de dados Mongo de vendas
  vendas-mongo:
    image: "mongo:latest"
    container_name: "vendas-mongo"
    hostname: "vendas-mongo"
    ports:
      - "27017:27017"
    networks:
      services-network-01:
        aliases:
          - vendas-mongo

  # App de vendas, que usa o Mongo
  venda-app:
    build: ./venda-app/
    container_name: "venda-app-instance"
    ports:
      - "8082:8082"
    depends_on:
      - vendas-mongo
      - eureka-server
      - produto-app
      - usuario-app
    networks:
      services-network-01:
        aliases:
          - vendas-service


# -------- CONFIGURAÇÃO -------- #

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    container_name: "eureka-server"
    networks:
      services-network-01:
        aliases:
          - eureka-server

  api-gateway:
    container_name: "api-gateway"
    build: ./api-gateway/
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - services-network-01




networks:
  services-network-01:
    name: services-network-01
    driver: bridge