global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    metrics_path: "/actuator/prometheus"
    scrape_interval: 1s
    static_configs:
      - targets:
          [
            "prometheus-app:9090",
            "prometheus:9090",
            "produtos-mysql-app-instance:80",
          ]

  - job_name: eureka
    scrape_interval: 1s
    eureka_sd_configs:
      - server: http://eureka-server:8671/eureka
      - refresh_interval: 1s
    #relabel_configs:
